_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "S3"
  DATAPATH: ""
  NUMBER_CLASSES: 2
  MULTILABEL: False
MODEL:
  TYPE: "vit"
  ONLYTEST: "False"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01