_BASE_: "../base-prompt.yaml"
RUN_N_TIMES: 1
DATA:
  NAME: "doc1"
  DATAPATH: ""
  NUMBER_CLASSES: 2
  MULTILABEL: False
MODEL:
  TYPE: "vit"
  ONLYTEST: "True"
  TESTPTH: "E:\\code\\VPTCode\\VPT\\originCode\\vpt-main\\vpt-main\\OutputDir\\doc2_vit_prompt_shallow_Dir\\doc2\\sup_vitb16_imagenet21k\\lr0.5_wd0.01\\run1\\last_model.pth"
SOLVER:
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.01